### ISSUE TITLE
Calcular as cordenadas mais próximas

### ISSUE THREAD

**Issue by Senhordim** [Senhordim/promoaki#13]
Baseado nas coordenadas recebidas efetuar um calculo buscando as coordenadas em um Raio de 5k.

Retornar uma lista com todas coordenadas.

**Comment by jean-felipe** [comment]
Uma pergunta sobre essa tarefa, o usuário vai escolher a distancia que quer as promoções ou terá um valor default?

**Comment by Senhordim** [comment]
Temos que ter um valor default, mas o usuário também vai poder escolher.
